# docker-compose.yml

version: '3'
  services:
    homeassistant:
      container-name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /hass/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # USB 장치 경로를 실제 ZBT-1 동글의 경로로 지정
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - TZ=Asia/Seoul
    restart: always
    network_mode: host
    privileged: true  # USB 장치에 대한 접근 권한 부여
